### ISSUE TITLE
Investigate disabling fielddata for name.* fields

### ISSUE THREAD

**Issue by orangejulius** [pelias/schema#100]
My understanding from reading through the [fielddata docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/fielddata.html) and from the AMA desk at Elasticon is that fielddata is only used for aggregations, sorting, and geo operations on geo fields.

Of those 3, as far as I know, we only do geo operations. However, fielddata is currently enabled on the name.\* fields and in dev is currently using 18GB of elasticsearch memory.

If it's really the case that none of our queries are fielddata for anything, I suspect disabling it would at least save us memory, and probably improve performance.

**Comment by riordan** [comment]
YESSSSSSSSSSSSSS

**Comment by Binternet** [comment]
Just checked out the `disable_fielddata` branch and tried to run wof importer (production branch) and this popped up:

`error: [dbclient] [400] type=strict_dynamic_mapping_exception, reason=mapping set to strict, dynamic introduction of [empire] within [parent] is not allowed`

**Comment by orangejulius** [comment]
Oh, good catch. I'll add that to the schema too!

**Comment by orangejulius** [comment]
A final signoff here, this causes a huge reduction in memory usage for Elasticsearch and a nice performance boost. I haven't tested a full planet build yet, but here is a printout of fielddata memory usage on a 4-node cluster before this change. After this change, it will be 0 bytes.

```
id                     host           ip             node               total name.default
C5Byr9OxTDqnNcANncjqgQ 172.20.108.159 172.20.108.159 Rigellian Recorder 8.9gb        2.6gb
_XYaH099SYK5EHHtfb6W-g 172.20.112.152 172.20.112.152 Solarman             9gb        2.6gb
BO9TGTGmT8SfxZAaBdybWA 172.20.62.101  172.20.62.101  Andrew Gervais     8.9gb        2.6gb
nj-Z42eiT7W4KoxgJRiO6A 172.20.94.205  172.20.94.205  Miracle Man        8.8gb        5.3gb
```

So that's **36GB** of memory in the cluster that was previously wasted for no use at all
