### ISSUE TITLE
Create index script fails on newer elasticsearch v2.2

### ISSUE THREAD

**Issue by bipin-nag** [pelias/schema#106]
I tried running it against latest elasticsearch v2.2 and it fails with error :

[put mapping] 	 pelias { [Error: [mapper_parsing_exception] analyzer on field [neighbourhood_id] must be set when search_analyzer is set]
  status: '400',
  message: '[mapper_parsing_exception] analyzer on field [neighbourhood_id] must be set when search_analyzer is set',
  path: '/pelias',
  query: {},
...

**Comment by orangejulius** [comment]
Hey @bipin-nag,
Thanks for reporting this. We have a [branch](https://github.com/pelias/schema/pull/101) with experimental changes for Elasticsearch 2.2 support, but we haven't had too much time to play with it. If you'd like to try it out and report back we would really appreciate it.

**Comment by orangejulius** [comment]
Hey @bipin-nag,
We just merged official support for Elasticsearch 2 to the master branches. If you have time we would love for you to check it out. It's very new so there easily could be some issues left. Anyways we hope you enjoy it, and we'll probably close this issue soon as we finish off the Elasticsearch 2 work

**Comment by bipin-nag** [comment]
Thanks @orangejulius for adding the support,
I tested it with recent v2.3.3 and it works fine. I will create new ticket if there are other issues.

**Comment by orangejulius** [comment]
Great, closing this issue then. :cake:
