### ISSUE TITLE
single character street names

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#129]
Street names such as "K Rd" are currently not retrievable from the index due to the single grams not being stored.

We are now storing single digits, so we should also store single characters.

Alternatively we can wait until we investigate the FST improvements in elasticsearch@2+ which might allow us to start storing single grams for all names.

The simplest solution would be to add another filter similar to [prefixZeroToSingleDigitNumbers](https://github.com/pelias/schema/blob/master/settings.js#L178-L182).

**Comment by orangejulius** [comment]
It looks like this works for autocomplete now with our transition to single grams with Elasticsearch 2!
http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1919%20L%20st
![screenshot_2016-07-02_18-07-14](https://cloud.githubusercontent.com/assets/111716/16542670/f1d164d0-407f-11e6-8fd0-a1e9e04c2a1c.png)

It also appears to work well for search even with ES 1.7
http://pelias.github.io/compare/#/v1/search%3Ftext=1919%20L%20St,%20springfield,%20OR
![screenshot_2016-07-02_18-08-16](https://cloud.githubusercontent.com/assets/111716/16542671/0ca7c538-4080-11e6-897a-9398a6c4aaaa.png)
