### ISSUE TITLE
Search Phase Exception Error

### ISSUE THREAD

**Issue by ktjaco** [pelias/schema#137]
I have done full data source imports (OA, OSM, GN, WOF) into my Pelias instance on a SDD. It was moved from the SSD to a HDD. It came to about 80-100GB in disk space. When the Pelias server starts and I try to make a basic query, `http://localhost:3100/v1/search?text=Canada`, I get a `SearchPhaseExecutionException[Failed to execute phase [query], all shards failed.` error.

This error doesn't occur on a SSD. I was thinking maybe this is a time out configuration setting for the Elasticsearch Pelias index but I can't seem to solve it. I got this error before on a HDD with large databases but works with no issue on smaller area imports.

I'm not getting any errors in the api console, just the browser when the query is made. Elasticsearch logs output the same error as the browser. I also set the `ES_HEAP_SIZE=28g` on a VM with 64GB.

**Comment by orangejulius** [comment]
Hey @curiousc0w,
Fortunately, this is probably not an issue with SSD vs HDD. At least I hope not, since nothing that I know of in Pelias (or Elasticsearch) cares about one versus the other.

Usually when people see this error it's due to a mismatch between the API code and the importers used to put data in Elasticsearch. Another common problem is forgetting to set up the Elasticsearch schema. The easiest thing to do might be to read through our [installation docs](https://github.com/pelias/pelias-doc/blob/master/installing.md), make sure your importers/api/schema code are all on the same branch (you probably want production), and up to date, and that something wasn't missed.

Another option to see what went wrong is to run an actual query against Elasticsearch, just as the API would, and you'll see a more detailed error message. 
First, you can use a change like this one to have the API print out the full query:
```diff
diff --cc query/search.js
index 75406fe,75406fe..a6e228c
--- a/query/search.js
+++ b/query/search.js
@@@ -127,7 -127,7 +127,9 @@@ function generateQuery( clean )
      textParser( clean.parsed_text, vs );
    }
  
--  return query.render( vs );
++  var q= query.render( vs );
++  console.log(JSON.stringify(q, null, 2));
++  return q;
  }
  
  // return diagonal distance in km, with min=1
```

Then, after restarting your API, hitting the API will cause a full query to be printed to the console. You can take that and run it directly against Elasticsearch with [the head plugin](https://mobz.github.io/elasticsearch-head/) or directly with curl, and it will show you a more full error message. Paste that full output here and I'm sure we can help you figure it out.

**Comment by curiousc0w** [comment]
I'm currently re-importing everything on an SSD but if I run into this error again I'll let you know. What do you mean when you say query against Elasticsearch? Do you mean ```localhost:9100/{query here}```?

**Comment by orangejulius** [comment]
Yeah, pretty much. The elasticsearch [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/_the_search_api.html) give some examples of how it works.

**Comment by curiousc0w** [comment]
I'm going to try creating a separate VM for Pelias builds and a separate VM for the Elasticsearch cluster. Before I had everything on one VM.

**Comment by orangejulius** [comment]
I'd be curious to know what the elasticsearch queries said. Did you have any luck with those? We see the general error you posted earlier (`SearchPhaseExecutionException[Failed to execute phase [query], all shards failed`), all the time, I'm almost certain from the Elasticsearch response we'll know what the problem is.

**Comment by curiousc0w** [comment]
I'm currently reimporting everything. If I receive the error again I'll post what the Elasticsearch query said. If you receive the "All Shard Failed" error all the time, what is the general cause on your end?

**Comment by orangejulius** [comment]
Usually it means one of the branches on the importer, API, or schema were not up to date with the others when building. So there's a good chance simply by reimporting you will fix things. We definitely have more work on our end to make the errors go away, or at least become more detectable.

**Comment by curiousc0w** [comment]
The imports finished and the error is back.

When I try to query Elasticsearch I get:

```bash
curl 'http://192.168.1.6:9200/pelias/_search?q=*&pretty'
{
  "error" : "SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed]",
  "status" : 503
}
```

API response when I search ```localhost:3100/v1/search?text=ottawa```.

```bash
[user@localhost api]$ npm start

> pelias-api@2.2.0 start /home/user/pelias/api
> node index.js

worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
worker: listening on 3100
2016-06-27T16:04:19.909Z - info: [api] Ignoring address parser output, regions only
2016-06-27T16:04:19.919Z - info: [api:controller:search] [req] endpoint=/v1/search text=canada, size=10, private=false, querySize=20
2016-06-27T16:04:19.925Z - debug: [api:controller:search] [ES req] index=pelias, searchType=dfs_query_then_fetch, must=[$=peliasIndexOneEdgeGram, $=1, $=canada], should=[$=peliasPhrase, type=phrase, $=1, $=2, $ref=$["body"]["query"]["filtered"]["query"]["bool"]["must"][0]["match"]["name.default"]["query"], $ref=$["body"]["query"]["filtered"]["query"]["bool"]["should"][0]["match"]["phrase.default"]["analyzer"], type=phrase, $ref=$["body"]["query"]["filtered"]["query"]["bool"]["should"][0]["match"]["phrase.default"]["boost"], $ref=$["body"]["query"]["filtered"]["query"]["bool"]["should"][0]["match"]["phrase.default"]["slop"], $ref=$["body"]["query"]["filtered"]["query"]["bool"]["must"][0]["match"]["name.default"]["query"], $=20, functions=[$=log1p, $=popularity, missing=1, $=1], score_mode=first, boost_mode=replace, $ref=$["body"]["query"]["filtered"]["query"]["bool"]["should"][0]["match"]["phrase.default"]["analyzer"], type=phrase, $ref=$["body"]["query"]["filtered"]["query"]["bool"]["should"][0]["match"]["phrase.default"]["boost"], $ref=$["body"]["query"]["filtered"]["query"]["bool"]["should"][0]["match"]["phrase.default"]["slop"], $ref=$["body"]["query"]["filtered"]["query"]["bool"]["must"][0]["match"]["name.default"]["query"], $=20, functions=[$=log1p, $=population, missing=1, $=2], score_mode=first, boost_mode=replace], $=20, $=true, sort=[_score]
2016-06-27T16:04:19.972Z - debug: [api:controller:search] [ES response] undefined
2016-06-27T16:04:19.992Z - info: [api] 127.0.0.1 - - [27/Jun/2016:16:04:19 +0000] "GET /v1/search?text=canada HTTP/1.1" 
```

**Comment by orangejulius** [comment]
Ah, this is the circuit breaker error. Basically Elasticsearch intentionally fails before it runs out of memory to...prevent it from failing? Look at the [circuit breaker](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/index-modules-fielddata.html) docs, and adjust the fielddata value to be a bit larger. I'm not sure if it will require a reindex or not.

I'll add a note to our installation docs as well, a couple people have run into this recently.

**Comment by curiousc0w** [comment]
Would I have to edit the elasticsearch.yml configuration file? Or one of the Pelias/Schema files?

**Comment by orangejulius** [comment]
This would all be in `elasticsearch.yml` I believe. The circuit breaker docs tell you exactly what to edit.

**Comment by curiousc0w** [comment]
Are ```"indices.breaker.fielddata.limit: 85%"``` and ```"indices.fielddata.cache.size: 75%"``` respectable settings?

**Comment by orangejulius** [comment]
That first line looks right, and it's the only one I added to my config.

I do remember having to fiddle with it a bit to find the right settings, I ended up setting a value in gigabytes (`indices.breaker.fielddata.limit: 50g` but a percentage is probably better. Let me know how it works out and I'll put a note in our installation docs.

**Comment by curiousc0w** [comment]
Those settings seemed to have fixed the ```[FIELDDATA] Data too large...``` errors. 

```SearchPhaseException``` errors seem to go away after 20 minutes or so. I suspect that Elasticsearch takes some time to start up. I've been monitoring Memory history (gnome-system-monitor) and I've noticed once I hit 30GB Memory usage  the error goes away and Elasticsearch health is green. 

Also, I've been playing around with additional configuration settings to [speed up Elasticsearch restart times](https://www.loggly.com/blog/nine-tips-configuring-elasticsearch-for-high-performance/).

> Tip #8: Recovery Properties Allow for Faster Restart Times
> 
> ES includes several recovery properties which improve both ElasticSearch cluster recovery and restart times. We have shown some sample values below. The value that will work best for you depends on the hardware you have in use, and the best advice we can give is to test, test, and test again.
> 
> cluster.routing.allocation.node_concurrent_recoveries:4
> 
> This property is how many shards per node are allowed for recovery at any moment in time. Recovering shards is a very IO-intensive operation, so you should set this value with real caution.
> 
> cluster.routing.allocation.node_initial_primaries_recoveries:18
> 
> This controls the number of primary shards initialized concurrently on a single node. The number of parallel stream of data transfer from node to recover shard from peer node is controlled by indices.recovery.concurrent_streams. The value below is setup for the Amazon instance, but if you have your own hardware you might be able to set this value much higher. The property max_bytes_per_sec (as its name suggests) determines how many bytes to transfer per second. This value again need to be configured according to your hardware.
> 
> indices.recovery.concurrent_streams: 4
> 
> indices.recovery.max_bytes_per_sec: 40mb
> 
> All of the properties described above get used only when the cluster is restarted.

**Comment by orangejulius** [comment]
Oooh that's a very interesting post, thanks for sharing. Its a bit old so perhaps some of those settings have changed but we will take a look at those for sure. Our production boxes take about 1 - 1.5 hours to load a snapshot, for reference. I haven't really checked to see what the load on the servers is during that time, so perhaps we can make them go faster with some tweaking.

**Comment by orangejulius** [comment]
I think everything in this issue is either resolved or old enough to consider resolved. If not, feel free to reopen.

**Comment by Binternet** [comment]
@orangejulius I'm trying to output the query again with
`console.log(q)` and getting `undefined`.

That's the current code snippet:

```
  var q = getQuery(vs);
  console.log('===============');
  console.log(q);
  console.log('===============');
```

and ideas?
