### ISSUE TITLE
output_mapping.js appears to print incomplete schema

### ISSUE THREAD

**Issue by easherma** [pelias/schema#161]
I've tried running the script and viewing the results in terminal as well as writing them to a file. In both cases, the output appears cut-off (though at different points in the expected output, depending on if I'm looking at the printed output vs writing stdout to a file: https://gist.github.com/easherma/b4f878f9ee67f9036f687890f16444f1

**Comment by easherma** [comment]
Additionally, expected.json doesn't appear to match what the current schema should look like (according to a gist @orangejulius sent me today)

**Comment by orangejulius** [comment]
Ahh, good catch, caught by the ol' `process.exit` issue with lots of data going through console.log. Fixed in #162
