### ISSUE TITLE
Elasticsearch 5 compatibility

### ISSUE THREAD

**Issue by cag** [pelias/schema#194]
So I have managed to get pelias working with es 5 by removing the following parameters:

`index_concurrency` and `refresh_interval` from `settings.index` (this is in the config repo)
Everything but `'type': 'geo_point'` from the `centroid.js` partial (seems like they just integrated the latlon and geohash features and removed the options: https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html)

Also here: https://github.com/pelias/config/issues/44

**Comment by cag** [comment]
Warning: upgrade to 5.x series could potentially break compatibility with 2.x because the latlon and geohash parameters exist in 2.x.

**Comment by rjpereira** [comment]
Apologise for asking , but from comment on : pelias/config#44 would seem that current master would work with 5.1, or not ?
Currently getting:

[mapper_parsing_exception] Mapping definition for [center_point] has unsupported parameters:  [geohash : true] [geohash_precision : 18] [lat_lon : true] [geohash_prefix : true]   

upon creation of the schema.... Any help welcome. Thx

**Comment by orangejulius** [comment]
Hey @rjpereira,
We aren't quite there yet. The list I just added to https://github.com/pelias/pelias/issues/461#issuecomment-282107762 shows what we have left to do.

Let's move all elasticsearch 5 discussion there.
