### ISSUE TITLE
performance tweaks

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#20]
read through this article and make some tweaks where necessary
http://www.elasticsearch.org/blog/performance-considerations-elasticsearch-indexing/

**Comment by dianashk** [comment]
Revisit when discussing schema redesign.

**Comment by orangejulius** [comment]
Looking at that article, we mostly already do everything it lists, or the information is out of date. There are certainly performance improvements we can make, but they will be more granular in the future.
