### ISSUE TITLE
create_index.js  Bad Request

### ISSUE THREAD

**Issue by longingchai** [pelias/schema#240]
"npm test" in schema all passed , but got "Bad Request" when I run "node scripts/create_index.js", can anyone help me to fix this problem ?

**Comment by orangejulius** [comment]
Hey @longingchai,
Thanks for reporting in. Can you share a little more information about your setup to help us figure out what might be wrong?

Some things that would help are:
* the full output of running `node scripts/create_index.js`
* Node.js version (`node -v`)
* Elasticsearch info (the full output of `curl http://localhost:9200`, substituting localhost for the location of your Elasticsearch server if needed, would be excellent)

**Comment by jeremy-prater** [comment]
I also get the same issue, I am using elastic search 5.6.0, which fails. If I use 2.4.0, it works fine. I believe it is because the create_index is using an older version of elasticsearch npm module, which calls HTTP POST instead of HTTP PUT for creating the index.

https://github.com/elastic/elasticsearch/pull/20001

**Comment by jeremy-prater** [comment]
I got past the API error by specifying the API version in the pelias_config, however there is another issue now.

{ apiVersion: '5.x',
  keepAlive: true,
  requestTimeout: '120000',
  hosts: 
   [ { env: 'development',
       protocol: 'http',
       host: 'localhost',
       port: 9200 } ],
  log: [ { type: 'stdio', level: [Object] } ] }

--------------
 create index 
--------------

[mapper_parsing_exception] Mapping definition for [center_point] has unsupported parameters:  [geohash : true] [geohash_precision : 18] [lat_lon : true] [geohash_prefix : true] 

{ error: 
   { root_cause: [ [Object] ],
     type: 'mapper_parsing_exception',
     reason: 'Failed to parse mapping [_default_]: Mapping definition for [center_point] has unsupported parameters:  [geohash : true] [geohash_precision : 18] [lat_lon : true] [geohash_prefix : true]',
     caused_by: 
      { type: 'mapper_parsing_exception',
        reason: 'Mapping definition for [center_point] has unsupported parameters:  [geohash : true] [geohash_precision : 18] [lat_lon : true] [geohash_prefix : true]' } },
  status: 400 }

**Comment by jeremy-prater** [comment]
I made a work around, not sure if it broke everthing else though. I managed to get the index created by commenting out lat_lon, and all 3 geohash elements from centroid.js. I believe they are provided automatically now.

{ apiVersion: '5.x',
  keepAlive: true,
  requestTimeout: '120000',
  hosts: 
   [ { env: 'development',
       protocol: 'http',
       host: 'localhost',
       port: 9200 } ],
  log: [ { type: 'stdio', level: [Object] } ] }

--------------
 create index 
--------------

[put mapping]    pelias { acknowledged: true,
  shards_acknowledged: true,
  index: 'pelias' } 


https://stackoverflow.com/questions/42385407/mapping-definition-for-location-has-unsupported-parameters-geohash-true

**Comment by orangejulius** [comment]
Hey @jeremy-prater,
That makes sense. We unfortunately [don't yet support Elasticsearch 5](https://github.com/pelias/pelias/issues/461). It's not on our immediate roadmap to work on, but we do want to do it eventually and anything we can do to take baby steps in that direction we want to do.

We do have a [PR](https://github.com/pelias/schema/pull/195) open to achieve Elasticsearch 5 compatibility. Can you take a look at that branch and see how the changes in there compare to the ones you made? Also if you could report on if those ES5 compatible changes work with ES2, that would be a huge help. Ideally we would be able to at least unofficially support ES5, while still working on ES2 soon.

**Comment by eldie1984** [comment]
For the POST error you can add the method you want to use to create the index. The line 19 of the file scripts/create_index.js look like this 
`client.indices.create( {method:'PUT', index: indexName, body: schema }, function( err, res ){`

**Comment by orangejulius** [comment]
Hey @eldie1984,
That's good to know. Do we have to do that though? I think changing the `pelias.json` configuration entry for the Elasticsearch version (as @jeremy-prater mentioned above), will take care of that, as the [Elasticsearch](https://www.npmjs.com/package/elasticsearch) module will then do the right thing based on that version. But if that's not true let me know, and we'll add it to the list of changes to make.

**Comment by jeremy-prater** [comment]
Correct, changing the apiVersion in pelias.json is sufficient to use the correct interface. I've been running importers all night. I'm up to ~140 mil indexes so far! I haven't tried the front end of Pelias yet, I've just been playing around in Kibana

![image](https://user-images.githubusercontent.com/5904518/30446181-39b5a038-993d-11e7-9f41-0bff149002e8.png)
