### ISSUE TITLE
[question] better to use doc_values rather than field_data on low memory installs

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#29]
worth re-reading:
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/geo-memory.html
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/doc-values.html

**Comment by missinglink** [comment]
this is helpful for installing in low memory environments such as the raspberry pi, this ticket can be easily resolved by documenting this in a README or wiki

**Comment by dianashk** [comment]
Closing as duplicate of #50
