### ISSUE TITLE
investigate ngrams

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#30]
ref: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html
ref: http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_index_time_search_as_you_type.html

ref: http://jontai.me/blog/2013/02/adding-autocomplete-to-an-elasticsearch-search-application/

**Comment by dianashk** [comment]
Related to pelias/api#74
