### ISSUE TITLE
[mapper_parsing_exception] No handler for type [string] declared on field [continent]

### ISSUE THREAD

**Issue by xarasbir** [pelias/schema#304]
I'm getting

`[mapper_parsing_exception] No handler for type [string] declared on field [continent]`

when running `create_index.js`

The server is running on ElasticSearch 6.2.4 on Ubuntu 16.04.4

**Comment by orangejulius** [comment]
Hey @xarasbir,
We don't support Elasticsearch 6 yet, but we are tracking progress towards it over in https://github.com/pelias/pelias/issues/719. It looks like you've hit some of the known issues, but of course we'd be happy to hear about any progress you make.

**Comment by xarasbir** [comment]
Thanks for the reply and the link. 
We've decided to use ES5. We'll upgrade to ES6 once Pelias fully support it.
