### ISSUE TITLE
Cannot create index with elastic search cloud 

### ISSUE THREAD

**Issue by pierreclr** [pelias/schema#312]
When trying to create index on elasticsearch, I get this message `Incorrect HTTP method for uri [/pelias] and method [POST], allowed: [HEAD, GET, PUT, DELETE]`.

I choose elastic.co (elastic search as a service) and wonder if this error is due to non backward compatibility ? 

Elastic version : 6.4

Should I use ES 2.4 or is there any pending work to support latest ES version ? 

Thank you

**Comment by missinglink** [comment]
We are currently supporting elasticsearch 2.x, thee are plans to upgrade to a more modern version to take advantage of some newer features but the work is not yet completed.

**Comment by missinglink** [comment]
I'm not familiar with elastic.co, so I can't comment there, I would assume that it's compatible with the Elasticsearch you download?

**Comment by pierreclr** [comment]
@missinglink elastic.co offers a fully managed elasticsearch (only 6.4) cluster coming along with side services

**Comment by missinglink** [comment]
We currently only support 2.x
