### ISSUE TITLE
Consider disabling bloom filters

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#33]
As per the advice in https://github.com/pelias/pelias/issues/5 it may be better for us to disable `bloom filters`.

More research/understanding needs to be done as it's not immediately clear about the benefits of doing so and any side-effects which might pop up.

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/index-modules-codec.html#bloom-postings

**Comment by riordan** [comment]
It appears by 2.0 this isn't really __a thing__ anymore. Closing.
