### ISSUE TITLE
`Av` abbreviation for avenue is not supported

### ISSUE THREAD

**Issue by orangejulius** [pelias/schema#335]
We need to add support for the `Av` abbreviation for Avenue. It's used fairly heavily in a lot of Open Addresses records. A notable example is `1320 E Edinger Av, Santa Ana, CA`:

[1320 E Edinger Av](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1320%20E%20Edinger%20Av,%20santa%20ana,%20CA)
![screenshot_2018-11-23_15-07-45](https://user-images.githubusercontent.com/111716/48928286-8f374480-ef31-11e8-8132-9d487a97e775.png)

[1320 E Edinger Ave](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1320%20E%20Edinger%20Ave,%20santa%20ana,%20CA)
![screenshot_2018-11-23_15-08-43](https://user-images.githubusercontent.com/111716/48928302-b261f400-ef31-11e8-8cfd-a82ab841b892.png)

The examples above are using the autocomplete endpoint, but this ties into issues such as https://github.com/pelias/pelias/issues/534 and https://github.com/pelias/pelias/issues/484, and probably requires https://github.com/pelias/schema/pull/310 to be merged so that we can properly use synonyms on the street field.

**Comment by sayanb1983** [comment]
Hi,

I am facing this same issue in my in-house Pelias server. Can you please recommend any fix which I can make in my current fork of schema which will fix this issue?

**Comment by orangejulius** [comment]
This was fixed in #356
