### ISSUE TITLE
Error while creating index

### ISSUE THREAD

**Issue by rbawaskar** [pelias/schema#34]
On running 
<code>
node scripts/create_index.js 
</code>

I am getting following error. I have elastic search installed and running properly. 

<code>
[put mapping] 	 pelias { [Error: RemoteTransportException[[White Queen][inet[/192.168.1.49:9300]][indices:admin/create]]; nested: IndexCreationException[[pelias] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find analyzer type [pelias-analysis] or tokenizer for [plugin]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [pelias-analysis]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.pelias-analysis.Pelias-analysisAnalyzerProvider]; ]
  message: 'RemoteTransportException[[White Queen][inet[/192.168.1.49:9300]][indices:admin/create]]; nested: IndexCreationException[[pelias] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find analyzer type [pelias-analysis] or tokenizer for [plugin]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [pelias-analysis]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.pelias-analysis.Pelias-analysisAnalyzerProvider]; ' } { error: 'RemoteTransportException[[White Queen][inet[/192.168.1.49:9300]][indices:admin/create]]; nested: IndexCreationException[[pelias] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find analyzer type [pelias-analysis] or tokenizer for [plugin]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [pelias-analysis]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.pelias-analysis.Pelias-analysisAnalyzerProvider]; ',
  status: 400 }
</code>

**Comment by rbawaskar** [comment]
tried with 
Elastic Search version 1.4.2 and 1.3.4

**Comment by missinglink** [comment]
Hi @rbawaskar apologies for the poor documentation, [this plugin](https://github.com/pelias/elasticsearch-plugin) needs to be installed first; which is why you are having issues, I will open a ticket to document that dependency better.

We're currently experiencing [this issue](https://github.com/pelias/elasticsearch-plugin/issues/5) with the plugin so I've assigned @hkrishna who is responsible for fixing the plugin and also ping @heffergm who may be able to provide information about the current status of the plugin and the correct install instructions which you can follow to avoid the above mentioned issue.

**Comment by heffergm** [comment]
You’ll want to use ES 1.3.4 and install the plugin via the following:

bin/plugin -url https://github.com/pelias/elasticsearch-plugin/blob/1.3.4/pelias-analysis.zip?raw=true -install pelias-analysis


--
Grant Heffernan

**Comment by rbawaskar** [comment]
@missinglink  @heffergm  Thanks guys for your support. 
Installed the plugin. 
Btw, one more question. (I am just starting to elasticsearch) 
How do i add the analyzer to settings mapping ?

**Comment by rbawaskar** [comment]
Even after installing the plugin, I am getting same error. :(

**Comment by heffergm** [comment]
You restarted elasticsearch after installing the plugin?

--
Grant Heffernan

**Comment by rbawaskar** [comment]
yes.

**Comment by heffergm** [comment]
Without being able to look at your environment it’s tough for me to say. The only reason you should see that error is if the plugin isn’t installed, so if you’re still getting it something isn’t set up correctly. You may want to take a look at the vagrant repository to build a test environment and get a handle on how things work.

--
Grant Heffernan

**Comment by missinglink** [comment]
@rbawaskar can you please confirm that the plugin installs without issue? sometimes the install emits and error message which is hard to spot.

Once the plugin has been installed it shows up for me here: http://localhost:9200/_cluster/stats?human&pretty

The last section of the json at that url has a property named 'plugins' inside which I have 'pelias-analysis' listed in my setup.

**Comment by missinglink** [comment]
re: your question about applying the plugin to an index, this is handled for you automatically if you use the default indeces (ie. if you use scripts/create_index.js)

The relevant parts are:
https://github.com/pelias/schema/blob/master/settings.js#L24 which should show up here: http://localhost:9200/_settings

once that has been defined and elasticsearch knows about the plugin, you can apply it on a per-field or per-index level like this: https://github.com/pelias/schema/blob/master/mappings/partial/suggest.json#L5

**Comment by rbawaskar** [comment]
@missinglink yes plugin shows up in stats. Thanks for the applying plugin to index part.

**Comment by missinglink** [comment]
ok cool, so is it working now, if not please post your error message again.

**Comment by rbawaskar** [comment]
@missinglink yes its working great now.
I was seeing plugin errors because there were multiple ES clusters on the network, and other clusters didn't had the plugin installed.

**Comment by jeannieh** [comment]
You might try the [schema plugin](http://schema.press/) as an alternative.
