### ISSUE TITLE
node: bad option: --max-http-header-size=16384

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#343]
Hey @orangejulius, it looks like something broke for me with https://github.com/pelias/schema/pull/340

I'm running node `11.7.0` and the PR says it supports `10.14+`, but I'm not able to create the Pelias index:

```
➜  portland-metro git:(master) pelias elastic create
node: bad option: --max-http-header-size=16384

➜  portland-metro git:(master) node --version
v11.7.0
```

**Comment by missinglink** [comment]
Oh, I'm guessing this is the version of nodejs running inside `docker` huh?

```
➜  portland-metro git:(master) pelias compose pull
Pulling libpostal     ... done
Pulling schema        ... done
Pulling api           ... done
Pulling placeholder   ... done
Pulling whosonfirst   ... done
Pulling openstreetmap ... done
Pulling openaddresses ... done
Pulling transit       ... done
Pulling csv-importer  ... done
Pulling polylines     ... done
Pulling interpolation ... done
Pulling pip           ... done
Pulling elasticsearch ... done
Pulling fuzzy-tester  ... done

➜  portland-metro git:(master) pelias elastic create
node: bad option: --max-http-header-size=16384
```

**Comment by missinglink** [comment]
Is it possibly caused by the `portland-synonyms` branch being one minor version back from `latest`?

```
docker run --rm -it pelias/schema:portland-synonyms node --version
v10.14.0
```

```
docker run --rm -it pelias/schema:latest node --version
v10.15.0
```

**Comment by missinglink** [comment]
What's the easiest way to rebuild that tag on dockerhub?
There are 3 projects on `pelias/docker` which use the new ES and the old nodejs, so I'd like to fix it ASAP.

**Comment by orangejulius** [comment]
I've just rebuilt the `portland-synonyms` tag, however we can now use the `master` branch in all the projects, since #310 is merged

**Comment by missinglink** [comment]
cool tx, https://github.com/pelias/docker/issues/67
