### ISSUE TITLE
Github allowing failing branches to be merged to master

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#353]
@orangejulius I think there is something wrong with our Travis-CI setup here?

Today I merged https://github.com/pelias/schema/pull/347, based off the build status reported on GitHub:

<img width="1020" alt="Screenshot 2019-03-18 at 13 59 45" src="https://user-images.githubusercontent.com/738069/54531662-24999100-4986-11e9-8a2c-15493b61a8dc.png">

... however, when I look on the Travis-CI site it shows that the build failed!
https://travis-ci.org/pelias/schema/builds/506178432

The good news is that the failure is not critical.

I suspect it was caused when the feature branch was merged or rebased into `master`, some changes had been made to master between when the feature branch was last touched and when it was merged, and the combination of the two meant that the test assertions needed to be changed.

Do you have any ideas how we might be able to get GitHub to fail in this situation?

**Comment by missinglink** [comment]
Additionally, when I opened https://github.com/pelias/schema/pull/352 to fix the tests, the PR button instantly showed as green and I was able to merge without waiting for the tests to run in CI.

**Comment by orangejulius** [comment]
I'm not sure how it happened, but it appears the link between the Pelias github org and TravisCI may have been broken. I went into the Pelias org settings and checked on TravisCI integration.
![image](https://user-images.githubusercontent.com/111716/54607966-11d69900-4a26-11e9-8fad-998c6057f270.png)


Eventually I wound up on this screen, where `pelias` and `pelias-deprecated` had ❌ next to them. After clicking the "grant permissions" button, things seem to be working better now. 

We will have to reset the requirements for merging branches, at lest in this repository. This can be done once Travis runs once for push and PR.

**Comment by missinglink** [comment]
🎉 awesome!
