### ISSUE TITLE
ampersand

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#366]
Ampersand punctuation is still using the old 'replacement' (`=>`) syntax for synonyms: 
https://github.com/pelias/schema/blob/master/synonyms/ampersand.txt

Contracting from `and => &` keeps the index small but doesn't allow autocomplete matching on prefixes such as `an`.

We should change this behaviour so that ampersand symbols are expanded rather than vice versa.

Example: "Newfoundland and Labrador", "Newfoundland an"

**Comment by orangejulius** [comment]
Definitely
