### ISSUE TITLE
Set store:false for phrase fields

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#376]
Since we disable returning the stored values of the phrase.* fields, we can probably disable store-ing any of those strings (which are duplicated in the name.* fields anyway if we want them) and save some bytes?

**Comment by orangejulius** [comment]
This is probably worth trying since it's basically a one line change.

In the long run, we should solve the phrase issues with #285, but that could take a while. This change is easy to make so why not? :)

**Comment by missinglink** [comment]
oh I think it's already set up correctly, I swear I have this same thought every 6 months 😄 

fields are `store:false` by default, we use the `_source` field to get the original inputs, and `phrase.*` is excluded from that.

- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-store.html
- https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-source-field.html

**Comment by jgmarce** [comment]
I don't agree that the original #285 "issues" were truly an inconvenience.  With a "jq" command to duplicate name.default to phrase.default elasticdump can be used as expected.   I find it convenient that phrase.default is hidden at the moment, as I now add tokens there that would look odd if exposed.   I imagine that phrase.default was hidden simply for aesthetic reasons.  How will the addition of many, many language alternatives effect these two fields.   In one way, it will be good to know if/when Pelias no longer uses the "_source.phrase" field, in which case I would only retain "phrase.default" and drop any language data from "name".
