### ISSUE TITLE
Issue with creating schema

### ISSUE THREAD

**Issue by srflaxu40** [pelias/schema#428]
Any reason for this error using the latest pelias schema repo master and ES 5.5?

```
[0;33m--------------
 create index 
--------------[0m

[class_cast_exception] java.lang.String cannot be cast to java.util.Map ```

**Comment by missinglink** [comment]
We actually dropped support for ES5 this week (as ES7 support is coming shortly)
Please try again using the latest version of ES6

**Comment by missinglink** [comment]
related: https://github.com/pelias/pelias/issues/719#issuecomment-559063037

**Comment by missinglink** [comment]
Please do a `pelias compose pull` and try again, it should still fail but with a descriptive error message :)
