### ISSUE TITLE
remove `_source.type` property

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#45]
there is a `type` property defined for `POI`, I'm not sure what it's used for? can it be removed?

ref: https://github.com/pelias/schema/blob/master/mappings/poi.js#L8

**Comment by hkrishna** [comment]
Yeah, I dont recollect why it was added in the first place.

**Comment by sevko** [comment]
Where does the `layer` property get injected into API results? It appears to duplicate the `type` value, and at least one of those is necessary if people want to distinguish between the types of results (admin boundaries, POIs, addresses).

**Comment by missinglink** [comment]
The semantics are a bit confusing here...

The `layer` and `type` params in the geoJSON are duplicated to give consumers time to change over, I wanted to deprecate `type` and use `layer` going forward as `_type` is an elasticsearch 'thing' that doesn't describe the function as efficiently as `layer` for API consumers.

more info: https://github.com/pelias/api/pull/76

Those `layer` and `type` properties get mapped from the document metadata and not from the document `_source` field: https://github.com/pelias/api/blob/master/helper/geojsonify.js#L25 (this has been merged recently as so you don't see the `.type` mapping there any more)

This issue is simply that there is a property inside `_source` called `type` which is very confusing in that a) it appears to not be used anywhere b) no-one knows what it does and c) it's confusingly similar to the `_type` metadata property used to describe the Lucene partition it is stored in.

**Comment by missinglink** [comment]
Since it's not explicitly supported by `(pelias/model).Document` it is safe to remove.

**Comment by sevko** [comment]
Alright, kill it. If anything it'll get caught by acceptance-tests.

**Comment by sevko** [comment]
This has been implemented, and `type` properties are no longer returned.

**Comment by missinglink** [comment]
Still seeing one in master https://github.com/pelias/schema/blob/master/mappings/poi.js#L10

**Comment by sevko** [comment]
hm, indeed. Why aren't they showing up in search results, I wonder?

**Comment by missinglink** [comment]
There is a mapping layer in `pelias/api` which sits between what is returned from `_source` and what appears in the `geoJSON`, also I believe that `null` fields are not indexed and therefore not returned in `_source`.

**Comment by missinglink** [comment]
this ticket was resolved some time ago, I checked the code to confirm, closing
