### ISSUE TITLE
Re think admin field analyzer (no tokenizer necessary)

### ISSUE THREAD

**Issue by hkrishna** [pelias/schema#46]
admin fields dont need to be tokenized. think ```New York``` and ```Great Britain```. We dont want to match ```New Jersey``` when the query is for ```New York``` because the ```whitespace``` tokenizer split ```New York``` into ```New``` and ```York```. 

However, we need more flexibility compared to ```keyword``` analyzer for string matching, fuzzy matching with distance of 1 or 2, case sensitivity etc and most of all being able to search ```new york, ny``` and partially match on admin2 field ```new york``` or admin1_abbr field ```ny```

**Comment by missinglink** [comment]
superseded by https://github.com/pelias/schema/issues/68

**Comment by dianashk** [comment]
@missinglink, is this still valid?
