### ISSUE TITLE
Use Docvalues when possible

### ISSUE THREAD

**Issue by hkrishna** [pelias/schema#50]
[geo_points](https://github.com/pelias/schema/blob/master/mappings/partial/centroid.js#L15), numeric fields (popularity, population of type ```multiplier```) can be changed to use [Doc Values](http://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html). 

Doc values are only about 10–25% slower than in-memory fielddata, they come with two major advantages:

* They live on disk instead of in heap memory. This allows you to work with quantities of fielddata that would normally be too large to fit into memory. In fact, your heap space ($ES_HEAP_SIZE) can now be set to a smaller size, which improves the speed of garbage collection and, consequently, node stability.
* Doc values are built at index time, not at search time. While in-memory fielddata has to be built on the fly at search time by uninverting the inverted index, doc values are prebuilt and much faster to initialize.

The trade-off is a larger index size and slightly slower fielddata access. Doc values are remarkably efficient, so for many queries you might not even notice the slightly slower speed. Combine that with faster garbage collections and improved initialization times and you may notice a net gain.

**Comment by missinglink** [comment]
Sounds good, not sure if I totally get the terminology, it's saying that our existing `fielddata` will be stored on disk instead of in the heap? AFAIK this only applies to the [centroid data](https://github.com/pelias/schema/blob/master/mappings/partial/centroid.js#L14)

Worth checking with @heffergm again, last time I checked our `fielddata` was very small and the issues we have with heap space are 99% to do with the completion suggester FST.

**Comment by heffergm** [comment]
Our field data is only ~1GB. As @missinglink says, all our memory requirement is down to the completion suggester.

**Comment by dianashk** [comment]
Related to pelias/schema#29

**Comment by orangejulius** [comment]
This might be good to do as part of pelias/pelias#325. In Elasticsearch 2, doc_values become the default, so it would be nice to know what the implications for performance will be _before_ we upgrade. @missinglink, have you looked at this as part of the upgrade yet? I'm curious to know what sort of difference it makes.

**Comment by missinglink** [comment]
closing this issue as we have already upgraded to elasticsearch 2
