### ISSUE TITLE
tweak boundary mapping per admin-level

### ISSUE THREAD

**Issue by sevko** [pelias/schema#51]
All admin-level boundary types [currently use](https://github.com/pelias/schema/blob/master/schema.js#L18,L23) the [boundary partial mapping](https://github.com/pelias/schema/blob/master/mappings/boundary.js), which incurs the following problems:

  * the `admin0` type contains `admin1` and `admin2` values and the `admin1` type contains an `admin2` value, which is incorrect
  * higher-level admin polygons, like `neighborhood`, don't have `locality` or `local_admin` names

Since different admin-levels have slightly different schemas, we probably won't be able to get away with just one mapping for them all. While we're updating these, we should get rid of the `gn_id` and `woe_id` attributes since they're not getting used for anything. I ran into problems with this when implementing pelias/quattroshapes-pipeline#21 (since the importer can't set `locality`/`local_admin` values for neighborhood polys).

**Comment by missinglink** [comment]
The idea of a record having a 'name' of 'United States' and also an 'admin0' of 'United States' is a bit weird, also having a 'neighborhood' property for a country record is obviously invalid.

So you're proposing removing redundant properties to avoid confusion and provide more clarity?

The original thinking behind the existing schema was that having unused fields in the mapping does not add any overhead on processing/storage and yet having a uniform schema makes writing queries much easier.

Roping in @hkrishna to this discussion as my assumption is that the more uniform the schema is, the easier it is to write queries against.

hk, what affect would admin-level specific mappings have on query composition?
ie. when a field is not present in the schema but specified in the query; vice versa.

For `gn_id` and `woe_id` if we're not using them they can get removed, although they don't take up any extra disk space or issues being there. Can we start importing these properties from quattro?

I tend to err on the side of simplicity/flexibility rather than performance/strictness, so in this case unless we can provide functionality which was missing previously, I would err on the side of simplicity and leave all `boundary` types the same.

Furthermore, considering our recent discussion in NYC I would like to aim to reduce 'poi' and 'boundary' down to a single schema to make it even easier to compose queries.

**Comment by missinglink** [comment]
It seems like the query logic is probably not an issue, unless @hkrishna can point out edge cases I haven't thought of?

```bash
#!/bin/bash

######################################################
# Query composition for admin-level-specific mappings
######################################################

ES='localhost:9200';

# Remove old data
curl -XDELETE "$ES/foobar?pretty=true";

# Create index, with mapping
curl -XPOST "$ES/foobar?pretty=true" -d '
{
  "mappings": {
    "admin0": {
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "admin1": {
      "properties": {
        "name": {
          "type": "string"
        },
        "admin0": {
          "type": "string"
        }
      }
    }
  }
}';

# Add an admin0
curl -XPOST "$ES/foobar/admin0/1?pretty=true" -d '
{
  "name": "United States"
}';

# Add an admin1
curl -XPOST "$ES/foobar/admin1/1?pretty=true" -d '
{
  "name": "Springfield",
  "admin0": "United States"
}';

# Refresh index
curl -XPOST "$ES/foobar/_refresh?pretty=true";

# Search by name
curl -XPOST "$ES/foobar/_search?pretty=true" -d '
{
  "query": {
    "filtered": {
      "query": {
        "match": {
          "name": "States"
        }
      }
    }
  }
}';

# Search by admin0
curl -XPOST "$ES/foobar/_search?pretty=true" -d '
{
  "query": {
    "filtered": {
      "query": {
        "match": {
          "admin0": "States"
        }
      }
    }
  }
}';
```

**Comment by sevko** [comment]
So, I'm not concerned about `admin0` having `admin1` and `admin2` names (though I think it's logically incorrect, and if we can change it without adding complexity we probably should) as much as `neighborhoods` being unable to have a `local_admin`/`locality` and `locality` a `local_admin` name respectively. As for the `gn_id` and `woe_id`, the overhead of having them there is negligible, but if they're not getting used I figure there isn't any point in keeping them around.

**Comment by hkrishna** [comment]
@missinglink you are correct in saying the query composition will simply ignore the missing fields in the document and only match against them when the document has them. So, we are good in that regard.

@sevko we aren't using ```gn_id``` and ```woe_id``` right now. But a document having a ```woe_id``` could be used as a tie-breaker in the scoring algorithm. However, thats an [issue](https://github.com/pelias/pelias/issues/75) in the backlog and not being worked on currently. So, we could take them out now and bring them back when needed (if that doesnt involve a lot of code change)

**Comment by sevko** [comment]
So, we're good to go on slightly different mappings per admin-level?

**Comment by hkrishna** [comment]
Yeah, we could make this change. But like @missinglink mentioned earlier - since we are planning on going towards one schema for all documents (points/shapes) does this work make sense in the short term? We should be mindful of spending time/effort (lines of code, tests, regressions, builds etc) in work thats not throw-away-work. So, lets plan accordingly?

**Comment by sevko** [comment]
That crossed my mind as well, since I'm looking to use `pelias-model` `Document`s in [pelias/quattroshapes-pipeline](https://github.com/pelias/quattroshapes-pipeline) and that isn't currently possible because they effectively represent POIs, not boundaries.

**Comment by missinglink** [comment]
I am still :-1: on this until as it appears to be a non-functional change.
I am totally :+1: on removing `gn_id` and `woe_id`.

Can we put the "individual mapping per layer" dicussion on hold until we've resolved the "what to use `_type` for" discussion?

**Comment by sevko** [comment]
> I am still :-1: on this until as it appears to be a non-functional change.

neighborhoods/localadmin/localities points are currently left without admin values for anything below admin2. *That's* what per-admin-level mappings would give us, and at the same time we'd be able to remove admin2 values from admin1 and admin2/admin1 values from admin0 (because it's wrong for them to be there).

**Comment by sevko** [comment]
We've tabled this discussion until we figure out whether we want to use a single `Document`-like object for all admin levels (as per @hkrishna ).

**Comment by missinglink** [comment]
Sorry I'm clearly still not understanding this properly, can you please explain what you mean by "neighborhoods/localadmin/localities points are currently left without admin values for anything below admin2. That's what per-admin-level mappings would give us.."?

The example below confirms what you say that this `neighborhood` does not have any values below `admin2`. What additional functionality would `per-admin-level` mappings give us? ie. what additional fields would be returned?

```javascript
GET http://pelias.mapzen.com/suggest/nearby?input=shoreditch&lat=51.5328850&lon=-0.0652280&layer=neighborhoods

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": "6196:_:_:gbr:shoreditch",
        "layer": "neighborhood",
        "name": "Shoreditch",
        "alpha3": "GBR",
        "admin0": "United Kingdom",
        "admin1": "England",
        "admin2": "Greater London",
        "text": "Shoreditch, Greater London"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.078583,
          51.526022
        ]
      }
    }
  ],
  "bbox": [
    -0.078583,
    51.526022,
    -0.078583,
    51.526022
  ],
  "date": 1429018497301
}
```

**Comment by sevko** [comment]
Since the [partial "boundary" mapping](https://github.com/pelias/schema/blob/master/mappings/boundary.js) that we use for *all* admin layers only defines `admin0`, `admin1`, and `admin2` values, it's not possible to set `locality`/`localadmin`/`neighborhood` values for any records. As a result, `neighborhood` records have neither a `locality` nor a `localadmin` name, and `locality` records don't have a `localadmin` name. To resolve that, we'd need to define separate mappings for `neighborhood` and `locality` that inherit from that `boundary` mapping, but additionally define those properties.

**Comment by sevko** [comment]
As an example of why this is problematic, a query for the SoHo neighborhood in New York
([`/search?input=soho, new york`](http://pelias.stage.mapzen.com/search?input=soho,%20new%20york)) returns the following results, one from geonames and another from Quattroshapes:

```javascript
{
    "properties": {
        "layer": "neighborhood",
        "admin0": "United States",
        "id": "24068:_:_:_:soho",
        "name": "Soho",
        "alpha3": "USA",
        "text": "Soho, New York County, NY",
        "admin1": "New York",
        "admin1_abbr": "NY",
        "admin2": "New York County"
    },
    "type": "Feature",
    "geometry": {
        "coordinates": [
            -74.008026,
            40.725323
        ],
        "type": "Point"
    }
},
{
    "properties": {
        "layer": "geoname",
        "locality": "New York",
        "admin0": "United States",
        "local_admin": "Manhattan",
        "id": "5138691",
        "name": "SoHo",
        "alpha3": "USA",
        "text": "SoHo, Manhattan, NY",
        "admin1": "New York",
        "admin1_abbr": "NY",
        "admin2": "New York County"
    },
    "type": "Feature",
    "geometry": {
        "coordinates": [
            -73.99961,
            40.72241
        ],
        "type": "Point"
    }
}
```

Where the geonames record has `locality`/`localadmin` like it's expected to, the Quattroshapes neighborhoods layer record *does* not, and they can't currently be set because that would violate the schema (again, since it only defines `admin0`, `admin1`, and `admin2` properties).

**Comment by missinglink** [comment]
oh right! now I see what you mean, I thought that the `poi` and `boundary` mappings were exactly the same except for the `boundaries` property.

I am totally `+1` on merging the 2 mapping so that we only have a single mapping, but I guess this is the antithesis of your proposal to have one separate mapping per layer?

Thanks for clearing that up ;)

**Comment by sevko** [comment]
I care more about just being able to set those values than how the underlying shema looks. I actually quite like the idea of one schema to, er, rule them all, since there's currently nothing that distinguishes the `admin` records from POIs. Then again, wouldn't they need separate mappings when/if we start importing polygon geometries since they'd have different shape types (polygon vs point)?

**Comment by missinglink** [comment]
ok cool, how do you feel about this? https://github.com/pelias/schema/pull/53

**Comment by dianashk** [comment]
No longer relevant. A lot has changed since the WOF integration.
