### ISSUE TITLE
MapperParsingException

### ISSUE THREAD

**Issue by hlhua** [pelias/schema#59]
Hello!

I tried to run the create_index.js as written in your documentation, but I had the following output:

`[put mapping]    pelias { message: 'MapperParsingException[mapping [_default_]]; nested: MapperParsingException[Unknown field [context]]; ' } { error: 'MapperParsingException[mapping [_default_]]; nested: MapperParsingException[Unknown field [context]]; ',
  status: 400 }`

What have I done wrong ?

**Comment by missinglink** [comment]
hi @hlhua I'm not sure what's going on, I tested again locally and it works as expected for me:

```bash
cd /tmp;
git clone git@github.com:pelias/schema.git;
cd schema;
npm install;
node scripts/drop_index.js ;
node scripts/create_index.js;
```

```bash
$ node --version
v0.10.36
```

```bash
$ curl localhost:9200
{
  "status" : 200,
  "name" : "Commando",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

could you please try again with the steps above and also reply with your nodejs and elasticsearch version numbers, that may be something to do with it..

**Comment by hlhua** [comment]
Hi @missinglink!

I noticed that my elasticsearch version was really outdated, so I updated it.

The script works now!

Thanks alot :)
