### ISSUE TITLE
Add Southwest, Southeast, Northwest, Northeast

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#62]
https://github.com/pelias/schema/blob/ngram/street_suffix.js

**Comment by riordan** [comment]
If you want to go to town: https://github.com/twain47/Nominatim/blob/80df4d3b560f5b1fd550dcf8cdc09a992b69fee0/module/tokenstringreplacements.inc

**Comment by missinglink** [comment]
opened https://github.com/pelias/schema/issues/63 to cover the rest of them
