### ISSUE TITLE
house numbers vs. punctuation

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#64]
house numbers such as `8/47` are matching the token `847` due to the punctuation being removed and the numbers being concatenated.

**Comment by orangejulius** [comment]
We appear to have the opposite problem now, a search for [8/47 Woonah Street](http://pelias.github.io/compare/#/v1/search%3Ftext=8/47%20woonah%20street) (which is a great street name by the way) also returns results like `47 Woonah Street`.

Presumably it was https://github.com/pelias/schema/pull/113 that cause this, right?

**Comment by dianashk** [comment]
Fixed!

![img_7208](https://user-images.githubusercontent.com/5446511/28969441-9bf58de6-78f2-11e7-97f5-7cc1a59cd781.PNG)
