### ISSUE TITLE
Create index leads to java.lang.ClassCastException exception in ES logs

### ISSUE THREAD

**Issue by hahla** [pelias/schema#69]
Setup was:
- installed latest develop branch
- new box on EC2: ubuntu 14.04, elastic search 1.6.0, java 1.7
- ran node scripts/create_index.js

Checking logs revealed following stack trace:
[2015-07-16 01:02:46,447][INFO ][gateway                  ] [Nemesis] recovered [1] indices into cluster_state
[2015-07-16 01:02:47,105][WARN ][index.warmer             ] [Nemesis] [pelias][0] failed to warm-up global ordinals for [center_point]
java.lang.ClassCastException: org.elasticsearch.index.fielddata.plain.GeoPointDoubleArrayIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexFieldData$Global
	at org.elasticsearch.search.SearchService$FieldDataWarmer$3.run(SearchService.java:953)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by missinglink** [comment]
thanks, I'll look in to it, I'm running elasticsearch `1.5.2` locally, it seems `1.6.0` has only just been released and we've not had time to test against it yet.

**Comment by missinglink** [comment]
the cause of this issue is this setting https://github.com/pelias/schema/blob/master/mappings/partial/centroid.js#L16 which worked fine in previous versions, the changelog for `1.6.0` is epic so will need more investigation

**Comment by missinglink** [comment]
@hahla I wasn't able to reproduce with the following setup, could you please provide more info?

```bash
peter@mini:/var/www/pelias/schema$ uname -a
Linux mini 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
```bash
peter@mini:/var/www/pelias/schema$ cat /etc/issue
Ubuntu 14.04.2 LTS \n \l
```
```bash
peter@mini:/var/www/pelias/schema$ node --version
v0.10.38
```
```bash
peter@mini:/var/www/pelias/schema$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```
```bash
peter@mini:/var/www/pelias/schema$ curl localhost:9200
{
  "status" : 200,
  "name" : "Omerta",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.6.0",
    "build_hash" : "cdd3ac4dde4f69524ec0a14de3828cb95bbb86d0",
    "build_timestamp" : "2015-06-09T13:36:34Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```
```bash
peter@mini:/var/www/pelias/schema$ node scripts/create_index.js 
[put mapping] 	 pelias 	 { acknowledged: true }
```

**Comment by missinglink** [comment]
oh wait, I see it in the logs now:

```bash
[2015-07-16 15:41:25,997][WARN ][index.warmer             ] [Omerta] [pelias][0] failed to warm-up global ordinals for [center_point]
java.lang.ClassCastException: org.elasticsearch.index.fielddata.plain.GeoPointDoubleArrayIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexFieldData$Global
```

it's just a warning message and nothing to worry about, it's just saying "you didn't have any data when I tried to warm up my index caches so I did nothing"

**Comment by missinglink** [comment]
wait, this! https://github.com/elastic/elasticsearch/issues/8044

**Comment by orangejulius** [comment]
Hey everyone,
There hasn't been any activity here in a while, and I think we've determined there's no issue, just a confusing Elasticsearch warning. If that's not true, feel free to reopen (note that Elasticsearch 2 is now required), and of course feel free to open new tickets for any other issues! :checkered_flag:
