### ISSUE TITLE
Allow override of default database name via pelias config file

### ISSUE THREAD

**Issue by heffergm** [pelias/schema#73]
The solution to the schema change scenario that came up yesterday in chat: allow the ability to change the database name that the API uses to issue requests to the backend via the pelias config file (currently hardcoded(?) as ‘pelias’). 

This would allow a manually rollout when there’s a breaking schema change where the live API would continue to point at the correct index until everything is in place to move to the new one.

**Comment by riordan** [comment]
This issue was moved to pelias/api#334
