### ISSUE TITLE
rethink `address_stop` filter

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#80]
as per https://github.com/pelias/api/issues/357 if a place name is composed entirely of [stop words](https://github.com/pelias/schema/blob/master/street_suffix.js#L2-L25) it results in 0 ngrams being inserted in to the index.

normally the ngram analyser would turn `1 aa street` -> `[ "1", "a", "aa" ]` (removing the `'street'`), we do this because otherwise the inverted index for `st`, `rd`, `roa`, `avenu` etc would be huge and result in slow queries.

in the case where the **entire** name is composed of stop words it ends up stripping **all** of the tokens and so we are left with: `avenue lane` -> `[]` or `vista center` -> `[]`.

in combination with using a `must` match condition means 0 results are returned:
```
{
   "query": {
      "match": {
         "name.default": {
            "analyzer": "peliasTwoEdgeGram",
            "query": "street avenue road"
         }
      }
   }
}
```

https://github.com/pelias/schema/blob/master/settings.js#L104

**Comment by riordan** [comment]
Joint issue: pelias/api#357

Resolved by #83
