### ISSUE TITLE
review kstem for autocomplete

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#89]
review `kstem` token filter for autocomplete analyses.

eg. 'walking' -> 'walk'
...but 'walki' => '??'

in cases where the stem is not strictly a prefix of the expansion, what happens then?

eg. 'peoples' -> 'person'
... but 'peop' -> '??'

**Comment by riordan** [comment]
Great catch

**Comment by riordan** [comment]
@orangejulius sez:
> Maybe this makes sense to run only when we've parse out that it's a category.
