### ISSUE TITLE
possible regex issue

### ISSUE THREAD

**Issue by missinglink** [pelias/schema#94]
The `remove_ordinals` regex seems to be wrong?
```
        "remove_ordinals" : {
          "type" : "pattern_replace",
          "pattern": "(([0-9])(st|nd|rd|th))",
          "replacement": "$2"
        },
```

this should really be `(([0-9]+)(st|nd|rd|th))` (with a plus sign) shouldn't it?

the weird thing is the test is passing here: https://github.com/pelias/schema/blob/master/integration/analyzer_peliasStreet.js#L27

ref: https://github.com/pelias/schema/blob/master/settings.js#L151

**Comment by orangejulius** [comment]
We fixed this in #96! :cherries:
